# Generated by Django 2.2.15 on 2020-08-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_nominations'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominations',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
