# Generated by Django 2.2.15 on 2020-08-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200808_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('producer', models.CharField(max_length=100)),
                ('marketer', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('day_due', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'contracts',
                'managed': False,
            },
        ),
    ]
